fix receipt bytes and path encoding
maticnetwork/matic.js pull request #109
Opened 2020-08-21 08:14 UTC by arthcp

2020-08-25 06:17 UTC, arthcp commented on src/libs/ProofsUtil.ts
> +          path: Buffer.concat([Buffer.from('00', 'hex'), rlp.encode(receipt.transactionIndex)]),
This code is common for pos and plasma flow in matic.js so separate changes are not needed for plasma.

2020-08-26 18:15 UTC, jdkanani approved these changes

2020-08-27 04:30 UTC, ptsayli requested changes

2020-08-27 04:30 UTC, ptsayli commented on src/libs/ProofsUtil.ts
> +          path: Buffer.concat([Buffer.from('00', 'hex'), rlp.encode(receipt.transactionIndex)]),
this change will fail verification on plasma contracts, either we need to make a change in plasma contracts,
or handle this change for only pos

2020-08-27 04:30 UTC, ptsayli commented on src/root/POSRootChainManager.ts
> +      options.network.abi('RootChainManager', 'pos'),
nice, you've set default plasma

2020-08-27 06:24 UTC, arthcp commented on src/libs/ProofsUtil.ts
> +          path: Buffer.concat([Buffer.from('00', 'hex'), rlp.encode(receipt.transactionIndex)]),
Existing proof generation is flawed, it fails when there are multiple transactions in the burn transaction block for both pos and plasma. This fixes the issue for both.

2020-08-27 06:27 UTC, ptsayli approved these changes

2020-08-27 06:29 UTC, merged