Ug feat size optimization
maticnetwork/matic.js pull request #184
Opened 2021-04-16 11:17 UTC by ujjwalgupta94

This PR reduces the size of bundled files being export with some other fixes listed below - 

1. Reduce bundle size
2. Create dev & env bundle and export them accordingly
3. remove bluebird.js
4. moves dev dependencies like typings to dev dependencies from dependecies
5. create script for dev & prod build

2021-04-16 11:44 UTC, ankitboghra commented
Suggestion: can replace `axios`(6.6K) with fetch(`node-fetch`)(1.3k)

2021-04-16 14:21 UTC, jdkanani commented
@ankitboghra @ujjwalgupta94 We faced few issues with node-fetch. @rahuldamodar94 can tell more about it. But we can look deeper.

2021-04-16 15:01 UTC, jdkanani requested changes

2021-04-19 07:35 UTC, ujjwalgupta94 commented on .gitignore
> +*.tgz
done

2021-04-19 07:36 UTC, ujjwalgupta94 commented on src/libs/ProofsUtil.ts
> +      // { concurrency: 20 }
added concurrency back with concurrency implementation in mapPromise

2021-04-21 16:19 UTC, jdkanani approved these changes

2021-05-12 07:38 UTC, merged