Testing & docs
maticnetwork/matic.js pull request #208
Opened 2021-06-01 05:13 UTC by fuzious

- tests added in mocha
- docs updated

2021-06-21 18:31 UTC, rahuldamodar94 commented on README.md
> +// Transder ether to an address
Transfer*

2021-06-21 18:33 UTC, rahuldamodar94 commented on README.md
> +await maticPOSClient.processExits(
add a comment explaining what the function does

2021-06-21 18:34 UTC, rahuldamodar94 commented on README.md
> +
add comment explaining what the function does

2021-06-21 18:34 UTC, rahuldamodar94 commented on README.md
> +
add comment

2021-06-21 18:36 UTC, rahuldamodar94 commented on package.json
> +    "@truffle/hdwallet-provider": "^1.0.43",
why is this done ?

2021-06-21 18:37 UTC, rahuldamodar94 commented on package.json
> +    "i": "^0.3.6",
?? why this needed ?

2021-06-21 18:37 UTC, rahuldamodar94 commented on package.json
> +    "npm": "^7.14.0",
??

2021-06-22 07:17 UTC, ujjwalgupta94 requested changes

2021-06-22 07:17 UTC, ujjwalgupta94 commented on src/libs/ProofsUtil.ts
> +          return Promise.resolve(val)
here only return val will work, as val itself is promise.

2021-06-24 12:20 UTC, rahuldamodar94 approved these changes

2021-06-28 12:48 UTC, ujjwalgupta94 approved these changes
looks good

2021-06-28 12:49 UTC, merged