versioned docs added
maticnetwork/matic.js pull request #244
Opened 2021-07-26 20:13 UTC by AmanRaj1608

Created two versions
- Next (Current)
- 2.0.x 

![image](https://user-images.githubusercontent.com/42104907/127052746-434b176f-2943-4c4c-b4cc-96ba36ffc994.png)

2021-07-29 03:13 UTC, ujjwalgupta94 requested changes

2021-07-29 11:08 UTC, AmanRaj1608 commented on docs/docs/plasma/ERC721/depositStatusFromTxHash.md
> +
Updated please review again @ujjwalgupta94

2021-08-03 14:55 UTC, AmanRaj1608 commented
- Moved the `depositStatusFromTxHash` from `plasma/ERC721` to `plasma`
- Removed the `next` version docs. All the 2.0.x files are in `versiones_docs/version-2.0.x`

2021-08-04 12:48 UTC, ujjwalgupta94 approved these changes

2021-08-04 12:49 UTC, merged