fix: audit fix and remove webpack
maticnetwork/matic.js pull request #435
Opened 2024-07-18 15:33 UTC by nitinmittal23

2024-07-21 03:56 UTC, py-zoid approved these changes

2024-08-05 12:57 UTC, ankitboghra commented on test/debug.js
> +  console.log(client.client.parent)
```suggestion

```

2024-08-05 12:59 UTC, ankitboghra requested changes

2024-08-05 12:59 UTC, ankitboghra commented on test/debug.js
> +  let tx = await client.depositEther(1, "0xD7Fbe63Db5201f71482Fa47ecC4Be5e5B125eF07", {
```suggestion
  const tx = await client.depositEther(1, "0xD7Fbe63Db5201f71482Fa47ecC4Be5e5B125eF07", {
```

2024-08-05 12:59 UTC, ankitboghra commented on tsconfig.json
> +}
empty line missing

2024-08-05 13:12 UTC, merged